project_structure/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('second_brain.urls', namespace='second_brain')),
    path('', include('insights.urls', namespace='insights')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

second_brain/urls.py
from django.urls import path
from . import views

app_name = 'second_brain'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('set_timezone', views.set_timezone, name='set_timezone'),
    path('fetch_weather/', views.fetch_weather, name='fetch_weather'),
    path('fetch_weather/<str:city>/', views.fetch_weather, name='fetch_weather_city'),
    path('get_last_tracked_city/', views.get_last_tracked_city, name='get_last_tracked_city'),
    # Event URLS
    path('daily-view', views.daily_view, name='daily_view'),
    path('daily-view/<int:year>/<int:month>/<int:day>/', views.daily_view, name='daily_view_specific'),
    path('weekly-calendar/', views.weekly_calendar, name='weekly_calendar'),
    path('weekly-calendar/<str:start_date>/', views.weekly_calendar, name='weekly_calendar_change_week'),
    path('monthly-calendar/', views.monthly_calendar, name='monthly_calendar'),
    path('monthly-calendar/<int:year>/<int:month>/', views.monthly_calendar, name='monthly_calendar_change_month'),
    path('create-event/', views.create_event, name='create_event'),
    path('manage-events/', views.manage_events, name='manage_events'),
    path('manage-events/<int:year>/', views.manage_events, name='manage_events_year'),
    path('events/<int:pk>/delete/', views.delete_event, name="delete_event"),
    path('events/<int:pk>/edit/', views.update_event, name="update_event"),
    path('get_event_status/', views.get_event_status, name='get_event_status'),
    # Task URLS
    path('tasks/<int:pk>/', views.task_detail, name='task_detail'),
    path('tasks/create/', views.create_task, name='create_task'),
    path('tasks/<int:pk>/edit/', views.update_task, name='update_task'),
    path('tasks/<int:pk>/delete/', views.delete_task, name='delete_task'),
    # Passion URLS
    path('passions/create/', views.passion_create, name='passion_create'),
    path('passions/<int:pk>/update/', views.passion_update, name='passion_update'),
    path('passions/<int:pk>/delete/', views.passion_delete, name='passion_delete'),
    path('passions/<int:passion_pk>/activity/create/', views.passion_activity_create, name='passion_activity_create'),
    path('passions/record_activity/', views.record_passion_activity, name='record_passion_activity'),
    path('passions/delete_activity/', views.delete_passion_activity, name='delete_passion_activity'),
    path('passions/update_passion_progress/<int:pk>/', views.update_passion_progress, name='update_passion_progress'),
    path('passions/category/add/', views.add_passion_category, name='add_passion_category'),
    # Quote URLS
    path('quotes/create/', views.quote_create, name='quote_create'),
    path('quotes/<int:pk>/star/', views.quote_star, name='quote_star'),
    path('quotes/get_starred/', views.get_starred, name='get_starred'),
    path('quotes/<int:pk>/delete/', views.quote_delete, name='quote_delete'),
    path('quotes/<int:pk>/edit/', views.quote_edit, name='quote_edit'),
    path('get_quotes_of_the_day/', views.get_quotes_of_the_day, name='get_quotes_of_the_day'),
    path('qotd_save/<int:quote_id>/', views.qotd_save, name='qotd_save'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from .views import signup, custom_login_view, CustomPasswordResetView, lemon_squeezy_webhook, link_existing_payment, check_payment_status, get_update_payment_url, update_color, get_color_selection, reset_color
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', custom_login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # django password reset urls
    path('password_reset/', CustomPasswordResetView.as_view(
        email_template_name='registration/custom_password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('mindmuse_lemon_squeezy_webhook/', lemon_squeezy_webhook, name='lemon_squeezy_webhook'),
    path('link_existing_payment/', link_existing_payment, name='link_existing_payment'),
    path('check_payment_status/', check_payment_status, name='check_payment_status'),
    path('get_update_payment_url/', get_update_payment_url, name='get_update_payment_url'),
    path('update_color/', update_color, name='update_color'),
    path('get_color_selection/', get_color_selection, name='get_color_selection'),
    path('reset_color/', reset_color, name='reset_color'),
]

templates/quotes/_qotd_save.html
<div class="modal-header">
    <h5 class="modal-title quote-modal" id="quoteModalLabel">Save Quote</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form id="quoteSaveForm" method="post" action="{% url 'second_brain:qotd_save' quote.id %}">
    {% csrf_token %}
    <div class="modal-body quote-modal">
        Save quote from '{{quote.author}}'?
    </div>
    <div class="modal-footer">
        <button type="submit" id="confirmSaveButton" class="btn btn-primary">Save quote</button>
    </div>
</form>

<style>

    form#quoteSaveForm .modal-footer .btn-primary {
        background-color: var(--btn-primary-bg);
        border-color: var(--btn-primary-border);
        width: 100%;
        height: 40px;
    }

    form#quoteSaveForm .modal-footer .btn-primary:hover {
        background-color: var(--btn-primary-bg);
        filter: brightness(90%);
    }

</style>

templates/quotes/_quote_confirm_delete.html
<div class="modal-body delete-modal">
    <h2>Delete {{ quote.author }}'s quote?</h2>
    <p>Are you sure you want to delete this quote?</p>
    <form method="POST" action="{% url 'second_brain:quote_delete' quote.pk %}">
        {% csrf_token %}
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger custom-btn-danger">Confirm</button>
        </div>
    </form>
</div>

<style>

    .delete-modal form {
        margin-bottom: -10px;
    }

    .delete-modal .custom-btn-danger {
        width: 100%;
        height: 40px;
    }

    .delete-modal .custom-btn-danger:hover {
        
    }

</style>

templates/quotes/_quote_edit_form.html
{% load widget_tweaks %}

<div class="modal-header">
  <h5 class="modal-title quote-modal" id="quoteModalLabel">Edit Quote</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="modal-body quote-modal">
  <div class="quote-card">
    <form id="quoteForm" method="post" action="{% url 'second_brain:quote_edit' quote.pk %}">
      {% csrf_token %}
      <p>
        <label for="quote-text">{{ form.quote.label }}:</label>
        <textarea id="quote-text" name="quote" class="small-form-input">{{ form.quote.value }}</textarea>
      </p>
      <p>
        <label for="quote-author">{{ form.author.label }}:</label>
        <input type="text" id="quote-author" name="author" value="{{ form.author.value }}" class="small-form-input">
      </p>
      <div class="modal-footer">
        <button type="submit" form="quoteForm" class="btn btn-primary">Update Quote</button>
      </div>
    </form>
  </div>
</div>

<style>

    .quote-modal {
        font-family: 'Roboto', sans-serif;
    }

    .quote-modal .modal-body {
        background-color: #f7f7f7;
        padding: 30px;
        border-radius: 12px;
    }

    .quote-modal .small-form-input {
        width: 100%;
        height: 40px;
        padding-left: 15px;
        border-radius: 5px;
        border: 2px solid var(--btn-primary-border);
        background-color: #E1E1E1;
    }

    .quote-modal textarea.small-form-input {
        height: auto;
        min-height: 80px;
    }

    .quote-modal input:focus,
    .quote-modal textarea:focus {
        border: 2px solid #E1E1E1;
    }

    .quote-modal .btn-primary {
        background-color: var(--btn-primary-bg);
        border-color: var(--btn-primary-border);
        width: 100%;
        height: 40px;
    }

    .quote-modal .btn-primary:hover {
        background-color: var(--btn-primary-bg);
        filter: brightness(90%);
    }

    .quote-modal p {
        margin-bottom: 15px;
    }

</style>

templates/quotes/_quote_form.html
{% load widget_tweaks %}

<div class="modal-header">
  <h5 class="modal-title quote-modal" id="quoteModalLabel">Add a Quote</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="modal-body quote-modal">
  <div class="quote-card">
    <form id="quoteForm" method="post" action="{% url 'second_brain:quote_create' %}">
        {% csrf_token %}
        <p>
            <label for="quote-text">Quote:</label>
            <textarea id="quote-text" name="quote" class="small-form-input"></textarea>
        </p>
        <p>
            <label for="quote-author">Author:</label>
            <input type="text" id="quote-author" name="author" class="small-form-input">
        </p>
        <div class="modal-footer">
            <button type="submit" form="quoteForm" class="btn btn-primary">Add Quote</button>
        </div>
    </form>
  </div>
</div>

<style>

    .quote-modal {
        font-family: 'Roboto', sans-serif;
    }

    .quote-modal .modal-body {
        background-color: #f7f7f7;
        padding: 30px;
        border-radius: 12px;
    }

    .quote-modal .small-form-input {
        width: 100%;
        height: 40px;
        padding-left: 15px;
        border-radius: 5px;
        border: 2px solid var(--btn-primary-border);
        background-color: #E1E1E1;
    }

    .quote-modal textarea.small-form-input {
        height: auto;
        min-height: 80px;
    }

    .quote-modal input:focus,
    .quote-modal textarea:focus {
        border: 2px solid #E1E1E1;
    }

    .quote-modal .btn-primary {
        background-color: var(--btn-primary-bg);
        border-color: var(--btn-primary-border);
        width: 100%;
        height: 40px;
    }

    .quote-modal .btn-primary:hover {
        background-color: var(--btn-primary-bg);
        filter: brightness(90%);
    }

    .quote-modal p {
        margin-bottom: 15px;
    }

</style>