project_structure/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('second_brain.urls', namespace='second_brain')),
    path('', include('insights.urls', namespace='insights')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

second_brain/urls.py
from django.urls import path
from . import views

app_name = 'second_brain'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('set_timezone', views.set_timezone, name='set_timezone'),
    path('fetch_weather/', views.fetch_weather, name='fetch_weather'),
    path('fetch_weather/<str:city>/', views.fetch_weather, name='fetch_weather_city'),
    path('get_last_tracked_city/', views.get_last_tracked_city, name='get_last_tracked_city'),
    # Event URLS
    path('daily-view', views.daily_view, name='daily_view'),
    path('daily-view/<int:year>/<int:month>/<int:day>/', views.daily_view, name='daily_view_specific'),
    path('weekly-calendar/', views.weekly_calendar, name='weekly_calendar'),
    path('weekly-calendar/<str:start_date>/', views.weekly_calendar, name='weekly_calendar_change_week'),
    path('monthly-calendar/', views.monthly_calendar, name='monthly_calendar'),
    path('monthly-calendar/<int:year>/<int:month>/', views.monthly_calendar, name='monthly_calendar_change_month'),
    path('create-event/', views.create_event, name='create_event'),
    path('manage-events/', views.manage_events, name='manage_events'),
    path('manage-events/<int:year>/', views.manage_events, name='manage_events_year'),
    path('events/<int:pk>/delete/', views.delete_event, name="delete_event"),
    path('events/<int:pk>/edit/', views.update_event, name="update_event"),
    path('get_event_status/', views.get_event_status, name='get_event_status'),
    # Task URLS
    path('tasks/<int:pk>/', views.task_detail, name='task_detail'),
    path('tasks/create/', views.create_task, name='create_task'),
    path('tasks/<int:pk>/edit/', views.update_task, name='update_task'),
    path('tasks/<int:pk>/delete/', views.delete_task, name='delete_task'),
    # Passion URLS
    path('passions/create/', views.passion_create, name='passion_create'),
    path('passions/<int:pk>/update/', views.passion_update, name='passion_update'),
    path('passions/<int:pk>/delete/', views.passion_delete, name='passion_delete'),
    path('passions/<int:passion_pk>/activity/create/', views.passion_activity_create, name='passion_activity_create'),
    path('passions/record_activity/', views.record_passion_activity, name='record_passion_activity'),
    path('passions/delete_activity/', views.delete_passion_activity, name='delete_passion_activity'),
    path('passions/update_passion_progress/<int:pk>/', views.update_passion_progress, name='update_passion_progress'),
    path('passions/category/add/', views.add_passion_category, name='add_passion_category'),
    # Quote URLS
    path('quotes/create/', views.quote_create, name='quote_create'),
    path('quotes/<int:pk>/star/', views.quote_star, name='quote_star'),
    path('quotes/get_starred/', views.get_starred, name='get_starred'),
    path('quotes/<int:pk>/delete/', views.quote_delete, name='quote_delete'),
    path('quotes/<int:pk>/edit/', views.quote_edit, name='quote_edit'),
    path('get_quotes_of_the_day/', views.get_quotes_of_the_day, name='get_quotes_of_the_day'),
    path('qotd_save/<int:quote_id>/', views.qotd_save, name='qotd_save'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from .views import signup, custom_login_view, CustomPasswordResetView, lemon_squeezy_webhook, link_existing_payment, check_payment_status, get_update_payment_url, update_color, get_color_selection, reset_color
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', custom_login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # django password reset urls
    path('password_reset/', CustomPasswordResetView.as_view(
        email_template_name='registration/custom_password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('mindmuse_lemon_squeezy_webhook/', lemon_squeezy_webhook, name='lemon_squeezy_webhook'),
    path('link_existing_payment/', link_existing_payment, name='link_existing_payment'),
    path('check_payment_status/', check_payment_status, name='check_payment_status'),
    path('get_update_payment_url/', get_update_payment_url, name='get_update_payment_url'),
    path('update_color/', update_color, name='update_color'),
    path('get_color_selection/', get_color_selection, name='get_color_selection'),
    path('reset_color/', reset_color, name='reset_color'),
]

second_brain/models.py
from django.db import models
from dateutil.relativedelta import relativedelta
from django.utils import timezone
import pytz
from datetime import timedelta
from users.models import CustomUser

# Create your models here.

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Task(models.Model):

    PRIORITY_CHOICES = (
        ('L', 'Low'),
        ('M', 'Medium'),
        ('H', 'High'),
    )

    CATEGORY_CHOICES = (
        ('R', 'Routine'),
        ('P', 'Physical'),
        ('M', 'Mental'),
        ('S', 'Spiritual'),
    )

    FREQUENCY_CHOICES = (
        ('D', 'Daily'),
        ('W', 'Weekly'),
        ('M', 'Monthly'),
    )

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICES, null=True, blank=True)
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES)
    frequency = models.CharField(max_length=1, choices=FREQUENCY_CHOICES)
    status = models.BooleanField(default=False)
    last_reset_date = models.DateField(default=timezone.now, null=True)
    last_reset_time = models.DateTimeField(default=timezone.now, null=True)

    def create_history(self):
        TaskHistory.objects.create(
            task=self,
            user=self.user,
            title=self.title,
            description=self.description,
            priority=self.priority,
            category=self.category,
            frequency=self.frequency,
            status=self.status,
            created_at=self.last_reset_time
        )

    def calculate_next_reset_date(self):
        # Get the current date in the user's timezone
        user_tz = pytz.timezone(self.user.timezone) #convert to pytz.timezone object
        now = timezone.localtime(timezone.now(), user_tz).date()
        
        if self.frequency == 'D':
            # For daily tasks, the next reset date is simply the next day
            return self.last_reset_date + timedelta(days=1)
        elif self.frequency == 'W':
            # For weekly tasks, find the next Sunday from the last reset date
            if self.last_reset_date.weekday() == 6:
                next_sunday = self.last_reset_date + timedelta(weeks=1)
            else:
                days_until_sunday = (6 - self.last_reset_date.weekday()) % 7
                next_sunday = self.last_reset_date + timedelta(days=days_until_sunday)
            return next_sunday
        elif self.frequency == 'M':
            # For monthly tasks, the next reset date is the first day of the next month
            last_reset_date = self.last_reset_date
            if last_reset_date.month == 12:
                next_month = last_reset_date.replace(year=last_reset_date.year+1, month=1, day=1)
            else:
                next_month = last_reset_date.replace(month=last_reset_date.month+1, day=1)
            return next_month

    def __str__(self):
        return f'{self.frequency} Task for {self.user}, "{self.title}"'

class TaskHistory(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    priority = models.CharField(max_length=1, choices=Task.PRIORITY_CHOICES, null=True, blank=True)
    category = models.CharField(max_length=1, choices=Task.CATEGORY_CHOICES)
    frequency = models.CharField(max_length=1, choices=Task.FREQUENCY_CHOICES)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField()

    def __str__(self):
        return f'{self.frequency} Task for {self.user}, created {self.created_at}, "{self.title}"'

class PassionCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Passion(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    category = models.ForeignKey(PassionCategory, on_delete=models.SET_NULL, null=True)
    color = models.CharField(max_length=7, default='#808080')

    def __str__(self):
        return self.name

class PassionActivity(models.Model):
    passion = models.ForeignKey(Passion, on_delete=models.CASCADE)
    date = models.DateField()
    duration = models.DurationField()

    class Meta:
        unique_together = ['passion', 'date']

    def __str__(self):
        return f'{self.passion.name} on {self.date}'

class Quote(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    quote = models.TextField()
    author = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.quote} from {self.author}'

class QuoteOfTheDay(models.Model):
    quote = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quote} from {self.author}'

second_brain/forms.py
from django import forms
from .models import Task, Passion, PassionActivity, Quote, Event
from  datetime import timedelta

class EventForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    start_time = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    end_time = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))

    class Meta:
        model = Event
        fields = ['title', 'description', 'start_date', 'start_time', 'end_date', 'end_time']

        labels = {
            'title': 'Event Title',
            'description': 'Event Description',
            'start_date': 'Start Date',
            'end_date': 'End Date',
            'start_time': 'Start Time',
            'end_time': 'End Time',
        }

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter event title'}),
            'description': forms.Textarea(attrs={'placeholder': 'Enter event description'}),
        }

class TaskForm(forms.ModelForm):
    title = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Enter task title'}))
    priority = forms.ChoiceField(choices=[('', 'Choose a priority')] + list(Task.PRIORITY_CHOICES), required=False)

    class Meta:
        model = Task
        fields = ['title', 'description', 'category', 'frequency', 'priority']

        labels = {
            'title': 'Task Title',
            'description': 'Task Description',
            'category': 'Task Category',
            'frequency': 'Task Frequency',
            'priority': 'Task Priority',
        }

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter task title'}),
            'description': forms.Textarea(attrs={'placeholder': 'Enter task description'}),
            'category': forms.Select(choices=[('', 'Choose a category')] + list(Task.CATEGORY_CHOICES)),
            'frequency': forms.Select(choices=Task.FREQUENCY_CHOICES),
            'priority': forms.Select(choices=[('', 'Choose a priority')] + list(Task.PRIORITY_CHOICES)),
        }

class PassionForm(forms.ModelForm):
    class Meta:
        model = Passion
        fields = ['name', 'category', 'description', 'color']

    new_category_name = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_category_name'].widget.attrs.update({
            'placeholder': 'New category name'
        })

hour_choices = [(i, f"{i} hours") for i in range(0, 25)]
minute_choices = [(i, f"{i} minutes") for i in range(0, 61, 5)]

class PassionActivityForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}))
    hour = forms.ChoiceField(choices=hour_choices, widget=forms.Select(attrs={'class': 'scrollable-dropdown'}))
    minute = forms.ChoiceField(choices=minute_choices, widget=forms.Select(attrs={'class': 'scrollable-dropdown'}))

    class Meta:
        model = PassionActivity
        fields = ['date', 'hour', 'minute']

    def clean(self):
        cleaned_data = super().clean()

        hour = int(cleaned_data.get("hour"))
        minute = int(cleaned_data.get("minute"))

        cleaned_data["duration"] = timedelta(hours=hour, minutes=minute)

        return cleaned_data

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'author']

templates/tasks/_create_task_form.html
{% load widget_tweaks %}

<div class="modal-body task-modal" style="background-color: #f7f7f7; border-radius: 12px;">
  <h2 class="text-center mb-4">Create Task</h2>
  <form method="POST" action="{% url 'second_brain:create_task' %}">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_title">{{ form.title.label }}</label>
      {{ form.title|add_class:"small-form-input" }}
    </div>
    <div class="mb-3">
      <label for="id_description">{{ form.description.label }}</label>
      {{ form.description|add_class:"small-form-input" }}
    </div>
    <div class="mb-3">
      <label for="id_category">{{ form.category.label }}</label>
      {{ form.category|add_class:"small-form-input" }}
    </div>
    <div class="mb-3">
      <label for="id_frequency">{{ form.frequency.label }}</label>
      {{ form.frequency|add_class:"small-form-input" }}
    </div>
    <div class="mb-3">
      <label for="id_priority">{{ form.priority.label }}</label>
      {{ form.priority|add_class:"small-form-input" }}
    </div>
    <div class="modal-footer">
      <button type="submit" class="btn btn-primary">Save</button>
    </div>
  </form>
</div>

<style>
  .task-modal {
    font-family: 'Roboto', sans-serif;
  }

  .task-modal .modal-body {
    background-color: #fff;
    padding: 30px;
    border-radius: 12px;
  }

  .task-modal .small-form-input {
    width: 100%;
    height: 40px;
    padding-left: 15px;
    border-radius: 5px;
    border: 2px solid var(--btn-primary-border);
    background-color: #E1E1E1;
  }

  .task-modal input:focus {
    border: 2px solid #E1E1E1;
  }

  .task-modal .btn-primary {
    background-color: var(--btn-primary-bg);
    border-color: var(--btn-primary-border);
    width: 100%;
    height: 40px;
  }

  .task-modal .btn-primary:hover {
    background-color: var(--btn-primary-bg);
    filter: brightness(90%);
  }

  .task-modal .mb-3 {
    margin-bottom: 15px;
  }
</style>

templates/tasks/_task_confirm_delete.html
<div class="modal-body">
    <h2>Delete {{ task.title }}?</h2>
    <p>Are you sure you want to delete this Task?</p>
    <form method="POST" action="{% url 'second_brain:delete_task' task.pk %}">
        {% csrf_token %}
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger">Confirm</button>
        </div>
    </form>
</div>

templates/tasks/_task_detail.html
<div class="modal-body">
  <p><strong>Description:</strong> {{ task.description }}</p>
  <p><strong>Priority:</strong> {{ task.get_priority_display }}</p>
  <p><strong>Category:</strong> {{ task.get_category_display }}</p>
  <p><strong>Frequency:</strong> {{ task.get_frequency_display }}</p>
  {% if task.completion_goal %}
  <p id="completion-count"><strong>Completion count:</strong> {{ task.completion_count }}</p>
  <p><strong>Completion goal:</strong> {{ task.completion_goal }}</p>
  {% endif %}
</div>
<div class="modal-footer">
  <div class="form-check modal-checkbox-container">
    <input class="form-check-input task-checkbox modal-checkbox" type="checkbox" id="modalTaskCheckbox{{ task.pk }}"
    onclick="updateTaskStatus(this, {{ task.pk }}, true);" {% if task.status %}checked{% endif %}>
    <label class="form-check-label" for="modalTaskCheckbox{{ task.pk }}">
      Mark as complete
    </label>
  </div>
</div>

<style>

.modal-checkbox + label:after {
  left: 7% !important;
}

.modal-checkbox:checked + label:after {
  left: 7% !important;
  border: solid #000 !important;
  border-width: 0 3px 3px 0 !important;
  opacity: 1 !important;
}

</style>

templates/tasks/_update_task_form.html
{% load widget_tweaks %}

<div class="modal-body update-task-modal">
  <div class="task-card">
    <h2 class="text-center mb-4">Update Task</h2>
    <form method="POST" action="{% url 'second_brain:update_task' task.pk %}">
      {% csrf_token %}
      <p>
        <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
        {{ form.title|add_class:"small-form-input" }}
      </p>
      <p>
        <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
        {{ form.description|add_class:"small-form-input" }}
      </p>
      <p>
        <label for="{{ form.category.id_for_label }}">{{ form.category.label }}</label>
        {{ form.category|add_class:"small-form-input" }}
      </p>
      <p>
        <label for="{{ form.frequency.id_for_label }}">{{ form.frequency.label }}</label>
        {{ form.frequency|add_class:"small-form-input" }}
      </p>
      <p>
        <label for="{{ form.priority.id_for_label }}">{{ form.priority.label }}</label>
        {{ form.priority|add_class:"small-form-input" }}
      </p>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </form>
  </div>
</div>

<style>
  .update-task-modal {
    font-family: 'Roboto', sans-serif;
  }

  .update-task-modal .modal-body {
    background-color: #fff;
    padding: 30px;
    border-radius: 12px;
  }

  .update-task-modal .small-form-input {
    width: 100%;
    height: 40px;
    padding-left: 15px;
    border-radius: 5px;
    border: 2px solid var(--btn-primary-border);
    background-color: #E1E1E1;
  }

  .update-task-modal input:focus {
    border: 2px solid #E1E1E1;
  }

  .update-task-modal .btn-primary {
    background-color: var(--btn-primary-bg);
    border-color: var(--btn-primary-border);
    width: 100%;
    height: 40px;
  }

  .update-task-modal .btn-primary:hover {
    background-color: var(--btn-primary-bg);
    filter: brightness(90%);
  }

  .update-task-modal .mb-3 {
    margin-bottom: 15px;
  }
</style>