project_structure/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('second_brain.urls', namespace='second_brain')),
    path('', include('insights.urls', namespace='insights')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

second_brain/urls.py
from django.urls import path
from . import views

app_name = 'second_brain'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('set_timezone', views.set_timezone, name='set_timezone'),
    path('fetch_weather/', views.fetch_weather, name='fetch_weather'),
    path('fetch_weather/<str:city>/', views.fetch_weather, name='fetch_weather_city'),
    path('get_last_tracked_city/', views.get_last_tracked_city, name='get_last_tracked_city'),
    # Event URLS
    path('daily-view', views.daily_view, name='daily_view'),
    path('daily-view/<int:year>/<int:month>/<int:day>/', views.daily_view, name='daily_view_specific'),
    path('weekly-calendar/', views.weekly_calendar, name='weekly_calendar'),
    path('weekly-calendar/<str:start_date>/', views.weekly_calendar, name='weekly_calendar_change_week'),
    path('monthly-calendar/', views.monthly_calendar, name='monthly_calendar'),
    path('monthly-calendar/<int:year>/<int:month>/', views.monthly_calendar, name='monthly_calendar_change_month'),
    path('create-event/', views.create_event, name='create_event'),
    path('manage-events/', views.manage_events, name='manage_events'),
    path('manage-events/<int:year>/', views.manage_events, name='manage_events_year'),
    path('events/<int:pk>/delete/', views.delete_event, name="delete_event"),
    path('events/<int:pk>/edit/', views.update_event, name="update_event"),
    path('get_event_status/', views.get_event_status, name='get_event_status'),
    # Task URLS
    path('tasks/<int:pk>/', views.task_detail, name='task_detail'),
    path('tasks/create/', views.create_task, name='create_task'),
    path('tasks/<int:pk>/edit/', views.update_task, name='update_task'),
    path('tasks/<int:pk>/delete/', views.delete_task, name='delete_task'),
    # Passion URLS
    path('passions/create/', views.passion_create, name='passion_create'),
    path('passions/<int:pk>/update/', views.passion_update, name='passion_update'),
    path('passions/<int:pk>/delete/', views.passion_delete, name='passion_delete'),
    path('passions/<int:passion_pk>/activity/create/', views.passion_activity_create, name='passion_activity_create'),
    path('passions/record_activity/', views.record_passion_activity, name='record_passion_activity'),
    path('passions/delete_activity/', views.delete_passion_activity, name='delete_passion_activity'),
    path('passions/update_passion_progress/<int:pk>/', views.update_passion_progress, name='update_passion_progress'),
    path('passions/category/add/', views.add_passion_category, name='add_passion_category'),
    # Quote URLS
    path('quotes/create/', views.quote_create, name='quote_create'),
    path('quotes/<int:pk>/star/', views.quote_star, name='quote_star'),
    path('quotes/get_starred/', views.get_starred, name='get_starred'),
    path('quotes/<int:pk>/delete/', views.quote_delete, name='quote_delete'),
    path('quotes/<int:pk>/edit/', views.quote_edit, name='quote_edit'),
    path('get_quotes_of_the_day/', views.get_quotes_of_the_day, name='get_quotes_of_the_day'),
    path('qotd_save/<int:quote_id>/', views.qotd_save, name='qotd_save'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from .views import signup, custom_login_view, CustomPasswordResetView, lemon_squeezy_webhook, link_existing_payment, check_payment_status, get_update_payment_url, update_color, get_color_selection, reset_color
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', custom_login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # django password reset urls
    path('password_reset/', CustomPasswordResetView.as_view(
        email_template_name='registration/custom_password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('mindmuse_lemon_squeezy_webhook/', lemon_squeezy_webhook, name='lemon_squeezy_webhook'),
    path('link_existing_payment/', link_existing_payment, name='link_existing_payment'),
    path('check_payment_status/', check_payment_status, name='check_payment_status'),
    path('get_update_payment_url/', get_update_payment_url, name='get_update_payment_url'),
    path('update_color/', update_color, name='update_color'),
    path('get_color_selection/', get_color_selection, name='get_color_selection'),
    path('reset_color/', reset_color, name='reset_color'),
]

second_brain/forms.py
from django import forms
from .models import Task, Passion, PassionActivity, Quote, Event
from  datetime import timedelta

class EventForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    start_time = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    end_time = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))

    class Meta:
        model = Event
        fields = ['title', 'description', 'start_date', 'start_time', 'end_date', 'end_time']

        labels = {
            'title': 'Event Title',
            'description': 'Event Description',
            'start_date': 'Start Date',
            'end_date': 'End Date',
            'start_time': 'Start Time',
            'end_time': 'End Time',
        }

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter event title'}),
            'description': forms.Textarea(attrs={'placeholder': 'Enter event description'}),
        }

class TaskForm(forms.ModelForm):
    title = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Enter task title'}))
    priority = forms.ChoiceField(choices=[('', 'Choose a priority')] + list(Task.PRIORITY_CHOICES), required=False)

    class Meta:
        model = Task
        fields = ['title', 'description', 'category', 'frequency', 'priority']

        labels = {
            'title': 'Task Title',
            'description': 'Task Description',
            'category': 'Task Category',
            'frequency': 'Task Frequency',
            'priority': 'Task Priority',
        }

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter task title'}),
            'description': forms.Textarea(attrs={'placeholder': 'Enter task description'}),
            'category': forms.Select(choices=[('', 'Choose a category')] + list(Task.CATEGORY_CHOICES)),
            'frequency': forms.Select(choices=Task.FREQUENCY_CHOICES),
            'priority': forms.Select(choices=[('', 'Choose a priority')] + list(Task.PRIORITY_CHOICES)),
        }

class PassionForm(forms.ModelForm):
    class Meta:
        model = Passion
        fields = ['name', 'category', 'description', 'color']

    new_category_name = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_category_name'].widget.attrs.update({
            'placeholder': 'New category name'
        })

hour_choices = [(i, f"{i} hours") for i in range(0, 25)]
minute_choices = [(i, f"{i} minutes") for i in range(0, 61, 5)]

class PassionActivityForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}))
    hour = forms.ChoiceField(choices=hour_choices, widget=forms.Select(attrs={'class': 'scrollable-dropdown'}))
    minute = forms.ChoiceField(choices=minute_choices, widget=forms.Select(attrs={'class': 'scrollable-dropdown'}))

    class Meta:
        model = PassionActivity
        fields = ['date', 'hour', 'minute']

    def clean(self):
        cleaned_data = super().clean()

        hour = int(cleaned_data.get("hour"))
        minute = int(cleaned_data.get("minute"))

        cleaned_data["duration"] = timedelta(hours=hour, minutes=minute)

        return cleaned_data

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'author']

templates/events/_create_event.html
<div class="modal-content event-modal">
    <div class="modal-header">
        <h5 class="modal-title">Create Event</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        <form id="createEventForm" method="post">
            {% csrf_token %}
            <div class="mb-3 event-form-group">
                <label for="title" class="event-form-label">Title:</label>
                <input type="text" name="title" id="title" class="event-form-input" required>
            </div>
            <div class="mb-3 event-form-group">
                <label for="start_date" class="event-form-label">Start Date:</label>
                <input type="text" name="start_date" id="start_date" class="event-form-input" required>
            </div>
            <div class="mb-3 event-form-group">
                <label for="end_date" class="event-form-label">End Date:</label>
                <input type="text" name="end_date" id="end_date" class="event-form-input" required>
            </div>
            <div class="mb-3 event-form-group">
                <label for="start_time" class="event-form-label">Start Time:</label>
                <input type="time" name="start_time" id="start_time" class="event-form-input" required>
            </div>
            <div class="mb-3 event-form-group">
                <label for="end_time" class="event-form-label">End Time:</label>
                <input type="time" name="end_time" id="end_time" class="event-form-input" required>
            </div>
        </form>
        <div class="modal-footer">
            <button type="submit" class="btn event-btn-primary" form="createEventForm">Create Event</button>
        </div>
    </div>
</div>

<div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered event-error-modal">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="errorModalLabel">Overlapping Events</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body event-error-body" id="errorModalBody">
                <h1>This Event overlaps with an existing event.</h1>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

<style>

    .event-modal {
        font-family: 'Roboto', sans-serif;
    }

    .event-modal .modal-body {
        background-color: #f7f7f7;
        padding: 30px;
        border-radius: 12px;
    }

    .event-modal .event-form-input {
        width: 100%;
        height: 40px;
        padding-left: 15px;
        border-radius: 5px;
        border: 2px solid var(--btn-primary-border);
        background-color: #E1E1E1;
    }

    .event-modal .event-form-input:focus {
        border: 2px solid #E1E1E1;
    }

    .event-modal .event-btn-primary {
        background-color: var(--btn-primary-bg);
        border-color: var(--btn-primary-border);
        width: 100%;
        height: 40px;
        color: var(--btn-text-color);
    }

    .event-modal .event-btn-primary:hover {
        background-color: var(--btn-primary-bg);
        filter: brightness(90%);
    }

    /* Error Modal Styles */
    .event-error-modal .modal-content {
        background-color: #f7f7f7;
    }

    .event-error-modal .modal-body {
        font-size: 18px;
    }

</style>

templates/events/_daily_view.html
{% load tz %}

<div class="modal-header">
    <h5 class="modal-title">Events for {{ today|date:"l, F j, Y" }}</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    {% if events %}
        <ul class="list-group">
            {% for event in events %}
                <li class="list-group-item">
                    {% with event.start_time|timezone:request.user.timezone as start_time %}
                    {% with event.end_time|timezone:request.user.timezone as end_time %}
                    {{ event.title }} - {{ start_time.time|time:"h:i A" }} - {{ end_time.time|time:"h:i A" }}
                    {% endwith %}
                    {% endwith %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No events today.</p>
    {% endif %}
</div>

templates/events/_event_confirm_delete.html
<div class="modal-body">
    <h2>Delete {{ event.title }}?</h2>
    <p>Are you sure you want to delete this Event?</p>
    <form id="deleteEventForm" method="POST" action="{% url 'second_brain:delete_event' event.id %}">
        {% csrf_token %}
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger">Confirm</button>
        </div>
    </form>
</div>

templates/events/_event_update.html
<div class="modal-content event-modal">
    <div class="modal-header">
        <h5 class="modal-title">Edit Event</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        <form id="updateEventForm" method="post">
            {% csrf_token %}
            <div class="mb-3 event-form-group">
                <label for="id_title" class="event-form-label">Title:</label>
                <input type="text" name="title" id="id_title" class="event-form-input" value="{{ event.title }}" required>
            </div>
            <div class="mb-3 event-form-group">
                <label for="id_start_date" class="event-form-label">Start Date:</label>
                <input type="text" name="start_date" id="id_start_date" class="event-form-input" value="{{ start_date }}" required>
            </div>
            <div class="mb-3 event-form-group">
                <label for="id_end_date" class="event-form-label">End Date:</label>
                <input type="text" name="end_date" id="id_end_date" class="event-form-input" value="{{ end_date }}" required>
            </div>
            <div class="mb-3 event-form-group">
                <label for="id_start_time" class="event-form-label">Start Time:</label>
                <input type="time" name="start_time" id="id_start_time" class="event-form-input" value="{{ start_time }}" required>
            </div>
            <div class="mb-3 event-form-group">
                <label for="id_end_time" class="event-form-label">End Time:</label>
                <input type="time" name="end_time" id="id_end_time" class="event-form-input" value="{{ end_time }}" required>
            </div>
        </form>
        <div class="modal-footer">
            <button type="submit" class="btn event-btn-primary" form="updateEventForm">Update Event</button>
        </div>
    </div>
</div>

<div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered event-error-modal">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="errorModalLabel">Overlapping Events</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body event-error-body" id="errorModalBody">
                <h1>This Event overlaps with an existing event.</h1>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

<style>

    .event-modal {
        font-family: 'Roboto', sans-serif;
    }

    .event-modal .modal-body {
        background-color: #f7f7f7;
        padding: 30px;
        border-radius: 12px;
    }

    .event-modal .event-form-input {
        width: 100%;
        height: 40px;
        padding-left: 15px;
        border-radius: 5px;
        border: 2px solid var(--btn-primary-border);
        background-color: #E1E1E1;
    }

    .event-modal .event-form-input:focus {
        border: 2px solid #E1E1E1;
    }

    .event-modal .event-btn-primary {
        background-color: var(--btn-primary-bg);
        border-color: var(--btn-primary-border);
        width: 100%;
        height: 40px;
        color: var(--btn-text-color);
    }

    .event-modal .event-btn-primary:hover {
        background-color: var(--btn-primary-bg);
        filter: brightness(90%);
    }

    /* Error Modal Styles */
    .event-error-modal .modal-content {
        background-color: #f7f7f7;
    }

    .event-error-modal .modal-body {
        font-size: 18px;
    }

</style>

templates/events/_manage_events.html
{% load tz %}
{% load custom_filters %}
{% load static %}

<div class="modal-header">
    <button style="background-color: {{ color_data|get_item:'tab-color' }} !important;" onclick="loadEventManageModal({{ current_year|add:-1 }})" class="btn btn-outline-secondary">
        <i class="fas fa-chevron-left" style="color: #FFFFFF;"></i>
    </button>
    <h5 class="modal-title me-2 ms-2">Events for {{ current_year }}</h5>
    <button style="background-color: {{ color_data|get_item:'tab-color' }} !important;" onclick="loadEventManageModal({{ current_year|add:1 }})" class="btn btn-outline-secondary">
        <i class="fas fa-chevron-right" style="color: #FFFFFF;"></i>
    </button>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="modal-body management-modal">
    {% if yearly_events_data %}
        {% for week_data in yearly_events_data %}
            {% if current_year == today.year and week_data.week_end < today %}
                <!-- Collapsible section for past weeks in the current year -->
                <div class="accordion mb-2" id="accordionPastWeek{{ forloop.counter }}">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="heading{{ forloop.counter }}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" 
                                    data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="false" 
                                    aria-controls="collapse{{ forloop.counter }}" style="color: black; background-color: lightgray;">
                                Past Week of {{ week_data.week_start|date:"F j" }} - {{ week_data.week_end|date:"F j, Y" }}
                            </button>
                        </h2>
                        <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse" 
                             aria-labelledby="heading{{ forloop.counter }}">
                            <div class="accordion-body">
                                {% if week_data.events %}
                                    {% regroup week_data.events by start_date as event_list %}
                                    {% for event_date in event_list %}
                                        <div class="card mb-2">
                                            <div class="card-header">{{ event_date.grouper|date:"l, F jS, Y" }}</div>
                                            <div class="card-body">
                                                {% for event in event_date.list %}
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="dropdown d-grid mb-1">
                                                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton{{ event.id }}" data-bs-toggle="dropdown" aria-expanded="false" style="width: 100%; display:block !important; white-space: normal !important; background-color: {{ color_data|get_item:'tab-color' }} !important;">
                                                                    {{ event.title }} - {{ event.start_time|time:"h:i A" }} - {{ event.end_time|time:"h:i A" }}
                                                                </button>
                                                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton{{ event.id }}" style="width: 100%;">
                                                                    <li><a class="dropdown-item green" href="#" onclick="loadEventUpdateModal({{ event.id }})">Modify</a></li>
                                                                    <li><a class="dropdown-item red" href="#" onclick="loadEventDeleteModal({{ event.id }})">Delete</a></li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    <p>No events for this week.</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <!-- Normal display for current and future weeks or other years -->
                <h6>Week of {{ week_data.week_start|date:"F j" }} - {{ week_data.week_end|date:"F j, Y" }}</h6>
                {% if week_data.events %}
                    {% regroup week_data.events by start_date as event_list %}
                    {% for event_date in event_list %}
                        <div class="card mb-2">
                            <div class="card-header">{{ event_date.grouper|date:"l, F jS, Y" }}</div>
                            <div class="card-body">
                                {% for event in event_date.list %}
                                    <div class="row">
                                        <div class="col">
                                            <div class="dropdown d-grid mb-1">
                                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton{{ event.id }}" data-bs-toggle="dropdown" aria-expanded="false" style="width: 100%; display:block !important; white-space: normal !important; background-color: {{ color_data|get_item:'tab-color' }} !important;">
                                                    {{ event.title }} - {{ event.start_time|time:"h:i A" }} - {{ event.end_time|time:"h:i A" }}
                                                </button>
                                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton{{ event.id }}" style="width: 100%;">
                                                    <li><a class="dropdown-item green" href="#" onclick="loadEventUpdateModal({{ event.id }})">Modify</a></li>
                                                    <li><a class="dropdown-item red" href="#" onclick="loadEventDeleteModal({{ event.id }})">Delete</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No events for this week.</p>
                {% endif %}
            {% endif %}
        {% endfor %}
    {% else %}
        <p>No events scheduled for this year.</p>
    {% endif %}
</div>





<style>

    .management-modal .dropdown-menu {
        background-color: #000000 !important;
    }

    .management-modal .dropdown-item {
        background-color: #000000 !important;
    }

    .management-modal .dropdown-item:hover {
        background-color: #000000 !important;
    }

    .management-modal .red:hover {
        background-color: #000000 !important;
        color: red;
    }

    .management-modal .green:hover {
        background-color: #000000 !important;
        color: #1ED760;
    }

</style>

templates/events/_monthly_calendar.html
{% if user.is_authenticated %}
	<div class="container mt-2">
	  <div class="row">
			<div class="col-md-12">
				<div class="d-flex justify-content-between mb-2">
					<a href="{% url 'second_brain:monthly_calendar_change_month' prev_year prev_month %}" class="btn btn-primary change-month">&lt; Previous</a>
					<h2>{{ current_month_name }} {{ current_year }}</h2>
					<a href="{% url 'second_brain:monthly_calendar_change_month' next_year next_month %}" class="btn btn-primary change-month">Next &gt;</a>
				</div>
				<table class="table table-bordered calendar-table">
					<thead>
						<tr>
							<th scope="col">Sun</th>
							<th scope="col">Mon</th>
							<th scope="col">Tue</th>
							<th scope="col">Wed</th>
							<th scope="col">Thu</th>
							<th scope="col">Fri</th>
							<th scope="col">Sat</th>
						</tr>
					</thead>
					<tbody>
						{% for week_data in calendar_data %}
							<tr>
								{% for day_data in week_data %}
									<td class="{{ day_data.date|date:'D' }}{% if day_data.event_count != None %} day-with-events{% endif %}" data-date="{{ day_data.date }}">
										{% if day_data.event_count != None %}
											<span>{{ day_data.date.day }}</span>
											{% if day_data.event_count > 0 %}
												<button onclick="loadDailyModal('{{ day_data.date.year }}', '{{ day_data.date.month }}', '{{ day_data.date.day }}');" class="badge btn btn-primary">{{ day_data.event_count }} Events</button>
											{% endif %}
										{% endif %}
									</td>
								{% endfor %}
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
  </div>
{% endif %}

templates/events/_weekly_calendar.html
{% load tz %}

<div class="modal-header">
    <h5 class="modal-title">Weekly view ({{ days.0.date|date:"F j, Y" }} - {{ days.6.date|date:"F j, Y" }})</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <div class="d-flex justify-content-between mb-4">
        <a href="{% url 'second_brain:weekly_calendar_change_week' prev_week_start|date:"Y-m-d" %}" class="btn btn-primary change-week">&laquo; Previous Week</a>
        <a href="{% url 'second_brain:weekly_calendar_change_week' next_week_start|date:"Y-m-d" %}" class="btn btn-primary change-week">Next Week &raquo;</a>
    </div>
    <div class="calendar weekly-calendar" style="overflow-x: auto;">
        <div class="row" style="width: 100%;">
            {% for day in days %}
                <div class="col">
                    <div class="card mb-2">
                        <div class="card-header">
                            {{ day.date|date:"D, F j" }}
                        </div>
                        <div class="card-body">
                            {% for event in events %}
                                {% with event.start_time|timezone:request.user.timezone as start_time %}
                                    {% with event.end_time|timezone:request.user.timezone as end_time %}
                                        {% if start_time.date|date:"Y-m-d" <= day.date|date:"Y-m-d" and end_time.date|date:"Y-m-d" >= day.date|date:"Y-m-d" %}
                                            <div class="event" style="border: 2px solid {{ event.color }}; border-radius: 5px; padding: 5px; margin-bottom: 5px;">
                                                <p>{{ event.title }}
                                                    {% if start_time.date|date:"Y-m-d" == day.date|date:"Y-m-d" %}
                                                        - {{ start_time.time|time:"h:i A" }}
                                                    {% endif %}
                                                    {% if end_time.date|date:"Y-m-d" == day.date|date:"Y-m-d" %}
                                                        - {{ end_time.time|time:"h:i A" }}
                                                    {% endif %}
                                                </p>
                                            </div>
                                        {% endif %}
                                    {% endwith %}
                                {% endwith %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>